language: generic
sudo: required
os:
  - linux
services:
  - docker
env:
  matrix:
    - EMACS_VERSION=snapshot
    - EMACS_VERSION=24.4
    - EMACS_VERSION=25.1
    - EMACS_VERSION=25.2
    - EMACS_VERSION=25.3
    - EMACS_VERSION=26.1
script:
  - make build
deploy:
  provider: script
  script: make push
  on:
    branch: master
